### ISSUE TITLE
Visited non-desktop programs remain in cache when switching to '"scan-path": true'

### ISSUE THREAD

**Issue by willemw12** [kspi/dmenu-frecency#11]
Not sure if this is a bug (maybe --read-app is supposed to do this), however it you start with '"scan-path": true'. Launch a non-desktop programs. Then switch to '"scan-path": true' and do a 'dmenu-frecency --read-app', then the visited non-desktop programs are still in the program/app cache. Expected a full refresh of the cache after the switch (automatically or with a new dmenu-frecency command line option).

**Comment by kspi** [comment]
This is by design: every visited program is saved to the 'visits' dictionary ant never cleared. This allows entering and saving custom command lines which are not in the list. If you want to clear it, you can remove the state file.

The current design is pretty complicated, I'll think about simplifying it.

**Comment by willemw12** [comment]
Also, you cannot remove a non-desktop app from the cache without deleting the whole cache (the state file).
